package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * HostSummaryByStatementLatency generated by hbm2java
 */
public class HostSummaryByStatementLatency implements java.io.Serializable {

	private HostSummaryByStatementLatencyId id;

	public HostSummaryByStatementLatency() {
	}

	public HostSummaryByStatementLatency(HostSummaryByStatementLatencyId id) {
		this.id = id;
	}

	public HostSummaryByStatementLatencyId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStatementLatencyId id) {
		this.id = id;
	}

}
