package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * HostSummaryByStatementType generated by hbm2java
 */
public class HostSummaryByStatementType implements java.io.Serializable {

	private HostSummaryByStatementTypeId id;

	public HostSummaryByStatementType() {
	}

	public HostSummaryByStatementType(HostSummaryByStatementTypeId id) {
		this.id = id;
	}

	public HostSummaryByStatementTypeId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStatementTypeId id) {
		this.id = id;
	}

}
