package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * InnodbBufferStatsBySchema generated by hbm2java
 */
public class InnodbBufferStatsBySchema implements java.io.Serializable {

	private InnodbBufferStatsBySchemaId id;

	public InnodbBufferStatsBySchema() {
	}

	public InnodbBufferStatsBySchema(InnodbBufferStatsBySchemaId id) {
		this.id = id;
	}

	public InnodbBufferStatsBySchemaId getId() {
		return this.id;
	}

	public void setId(InnodbBufferStatsBySchemaId id) {
		this.id = id;
	}

}
