package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * InnodbLockWaits generated by hbm2java
 */
public class InnodbLockWaits implements java.io.Serializable {

	private InnodbLockWaitsId id;

	public InnodbLockWaits() {
	}

	public InnodbLockWaits(InnodbLockWaitsId id) {
		this.id = id;
	}

	public InnodbLockWaitsId getId() {
		return this.id;
	}

	public void setId(InnodbLockWaitsId id) {
		this.id = id;
	}

}
