package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * InnodbBufferStatsByTable generated by hbm2java
 */
public class InnodbBufferStatsByTable implements java.io.Serializable {

	private InnodbBufferStatsByTableId id;

	public InnodbBufferStatsByTable() {
	}

	public InnodbBufferStatsByTable(InnodbBufferStatsByTableId id) {
		this.id = id;
	}

	public InnodbBufferStatsByTableId getId() {
		return this.id;
	}

	public void setId(InnodbBufferStatsByTableId id) {
		this.id = id;
	}

}
