package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * IoGlobalByFileByBytes generated by hbm2java
 */
public class IoGlobalByFileByBytes implements java.io.Serializable {

	private IoGlobalByFileByBytesId id;

	public IoGlobalByFileByBytes() {
	}

	public IoGlobalByFileByBytes(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

	public IoGlobalByFileByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByBytesId id) {
		this.id = id;
	}

}
