package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * IoGlobalByFileByLatency generated by hbm2java
 */
public class IoGlobalByFileByLatency implements java.io.Serializable {

	private IoGlobalByFileByLatencyId id;

	public IoGlobalByFileByLatency() {
	}

	public IoGlobalByFileByLatency(IoGlobalByFileByLatencyId id) {
		this.id = id;
	}

	public IoGlobalByFileByLatencyId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByLatencyId id) {
		this.id = id;
	}

}
