package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * IoGlobalByWaitByBytes generated by hbm2java
 */
public class IoGlobalByWaitByBytes implements java.io.Serializable {

	private IoGlobalByWaitByBytesId id;

	public IoGlobalByWaitByBytes() {
	}

	public IoGlobalByWaitByBytes(IoGlobalByWaitByBytesId id) {
		this.id = id;
	}

	public IoGlobalByWaitByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByWaitByBytesId id) {
		this.id = id;
	}

}
