package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * IoGlobalByWaitByLatency generated by hbm2java
 */
public class IoGlobalByWaitByLatency implements java.io.Serializable {

	private IoGlobalByWaitByLatencyId id;

	public IoGlobalByWaitByLatency() {
	}

	public IoGlobalByWaitByLatency(IoGlobalByWaitByLatencyId id) {
		this.id = id;
	}

	public IoGlobalByWaitByLatencyId getId() {
		return this.id;
	}

	public void setId(IoGlobalByWaitByLatencyId id) {
		this.id = id;
	}

}
