package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * MemoryByUserByCurrentBytes generated by hbm2java
 */
public class MemoryByUserByCurrentBytes implements java.io.Serializable {

	private MemoryByUserByCurrentBytesId id;

	public MemoryByUserByCurrentBytes() {
	}

	public MemoryByUserByCurrentBytes(MemoryByUserByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByUserByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByUserByCurrentBytesId id) {
		this.id = id;
	}

}
