package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * MemoryByThreadByCurrentBytes generated by hbm2java
 */
public class MemoryByThreadByCurrentBytes implements java.io.Serializable {

	private MemoryByThreadByCurrentBytesId id;

	public MemoryByThreadByCurrentBytes() {
	}

	public MemoryByThreadByCurrentBytes(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByThreadByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

}
