package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * Metrics generated by hbm2java
 */
public class Metrics implements java.io.Serializable {

	private MetricsId id;

	public Metrics() {
	}

	public Metrics(MetricsId id) {
		this.id = id;
	}

	public MetricsId getId() {
		return this.id;
	}

	public void setId(MetricsId id) {
		this.id = id;
	}

}
