package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * Processlist generated by hbm2java
 */
public class Processlist implements java.io.Serializable {

	private ProcesslistId id;

	public Processlist() {
	}

	public Processlist(ProcesslistId id) {
		this.id = id;
	}

	public ProcesslistId getId() {
		return this.id;
	}

	public void setId(ProcesslistId id) {
		this.id = id;
	}

}
