package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * SchemaObjectOverview generated by hbm2java
 */
public class SchemaObjectOverview implements java.io.Serializable {

	private SchemaObjectOverviewId id;

	public SchemaObjectOverview() {
	}

	public SchemaObjectOverview(SchemaObjectOverviewId id) {
		this.id = id;
	}

	public SchemaObjectOverviewId getId() {
		return this.id;
	}

	public void setId(SchemaObjectOverviewId id) {
		this.id = id;
	}

}
