package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * SchemaIndexStatistics generated by hbm2java
 */
public class SchemaIndexStatistics implements java.io.Serializable {

	private SchemaIndexStatisticsId id;

	public SchemaIndexStatistics() {
	}

	public SchemaIndexStatistics(SchemaIndexStatisticsId id) {
		this.id = id;
	}

	public SchemaIndexStatisticsId getId() {
		return this.id;
	}

	public void setId(SchemaIndexStatisticsId id) {
		this.id = id;
	}

}
