package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * SchemaTableLockWaits generated by hbm2java
 */
public class SchemaTableLockWaits implements java.io.Serializable {

	private SchemaTableLockWaitsId id;

	public SchemaTableLockWaits() {
	}

	public SchemaTableLockWaits(SchemaTableLockWaitsId id) {
		this.id = id;
	}

	public SchemaTableLockWaitsId getId() {
		return this.id;
	}

	public void setId(SchemaTableLockWaitsId id) {
		this.id = id;
	}

}
