package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * SchemaUnusedIndexes generated by hbm2java
 */
public class SchemaUnusedIndexes implements java.io.Serializable {

	private SchemaUnusedIndexesId id;

	public SchemaUnusedIndexes() {
	}

	public SchemaUnusedIndexes(SchemaUnusedIndexesId id) {
		this.id = id;
	}

	public SchemaUnusedIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaUnusedIndexesId id) {
		this.id = id;
	}

}
