package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * SchemaTableStatisticsWithBuffer generated by hbm2java
 */
public class SchemaTableStatisticsWithBuffer implements java.io.Serializable {

	private SchemaTableStatisticsWithBufferId id;

	public SchemaTableStatisticsWithBuffer() {
	}

	public SchemaTableStatisticsWithBuffer(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

	public SchemaTableStatisticsWithBufferId getId() {
		return this.id;
	}

	public void setId(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

}
