package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * SchemaRedundantIndexes generated by hbm2java
 */
public class SchemaRedundantIndexes implements java.io.Serializable {

	private SchemaRedundantIndexesId id;

	public SchemaRedundantIndexes() {
	}

	public SchemaRedundantIndexes(SchemaRedundantIndexesId id) {
		this.id = id;
	}

	public SchemaRedundantIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaRedundantIndexesId id) {
		this.id = id;
	}

}
