package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * SessionSslStatus generated by hbm2java
 */
public class SessionSslStatus implements java.io.Serializable {

	private SessionSslStatusId id;

	public SessionSslStatus() {
	}

	public SessionSslStatus(SessionSslStatusId id) {
		this.id = id;
	}

	public SessionSslStatusId getId() {
		return this.id;
	}

	public void setId(SessionSslStatusId id) {
		this.id = id;
	}

}
