package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * Session generated by hbm2java
 */
public class Session implements java.io.Serializable {

	private SessionId id;

	public Session() {
	}

	public Session(SessionId id) {
		this.id = id;
	}

	public SessionId getId() {
		return this.id;
	}

	public void setId(SessionId id) {
		this.id = id;
	}

}
