package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * StatementsWithErrorsOrWarnings generated by hbm2java
 */
public class StatementsWithErrorsOrWarnings implements java.io.Serializable {

	private StatementsWithErrorsOrWarningsId id;

	public StatementsWithErrorsOrWarnings() {
	}

	public StatementsWithErrorsOrWarnings(StatementsWithErrorsOrWarningsId id) {
		this.id = id;
	}

	public StatementsWithErrorsOrWarningsId getId() {
		return this.id;
	}

	public void setId(StatementsWithErrorsOrWarningsId id) {
		this.id = id;
	}

}
