package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * StatementsWithFullTableScans generated by hbm2java
 */
public class StatementsWithFullTableScans implements java.io.Serializable {

	private StatementsWithFullTableScansId id;

	public StatementsWithFullTableScans() {
	}

	public StatementsWithFullTableScans(StatementsWithFullTableScansId id) {
		this.id = id;
	}

	public StatementsWithFullTableScansId getId() {
		return this.id;
	}

	public void setId(StatementsWithFullTableScansId id) {
		this.id = id;
	}

}
