package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * StatementAnalysis generated by hbm2java
 */
public class StatementAnalysis implements java.io.Serializable {

	private StatementAnalysisId id;

	public StatementAnalysis() {
	}

	public StatementAnalysis(StatementAnalysisId id) {
		this.id = id;
	}

	public StatementAnalysisId getId() {
		return this.id;
	}

	public void setId(StatementAnalysisId id) {
		this.id = id;
	}

}
