package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * UserSummaryByFileIo generated by hbm2java
 */
public class UserSummaryByFileIo implements java.io.Serializable {

	private UserSummaryByFileIoId id;

	public UserSummaryByFileIo() {
	}

	public UserSummaryByFileIo(UserSummaryByFileIoId id) {
		this.id = id;
	}

	public UserSummaryByFileIoId getId() {
		return this.id;
	}

	public void setId(UserSummaryByFileIoId id) {
		this.id = id;
	}

}
