package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * UserSummaryByStages generated by hbm2java
 */
public class UserSummaryByStages implements java.io.Serializable {

	private UserSummaryByStagesId id;

	public UserSummaryByStages() {
	}

	public UserSummaryByStages(UserSummaryByStagesId id) {
		this.id = id;
	}

	public UserSummaryByStagesId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStagesId id) {
		this.id = id;
	}

}
