package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * UserSummaryByStatementLatency generated by hbm2java
 */
public class UserSummaryByStatementLatency implements java.io.Serializable {

	private UserSummaryByStatementLatencyId id;

	public UserSummaryByStatementLatency() {
	}

	public UserSummaryByStatementLatency(UserSummaryByStatementLatencyId id) {
		this.id = id;
	}

	public UserSummaryByStatementLatencyId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStatementLatencyId id) {
		this.id = id;
	}

}
