package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * UserSummaryByStatementType generated by hbm2java
 */
public class UserSummaryByStatementType implements java.io.Serializable {

	private UserSummaryByStatementTypeId id;

	public UserSummaryByStatementType() {
	}

	public UserSummaryByStatementType(UserSummaryByStatementTypeId id) {
		this.id = id;
	}

	public UserSummaryByStatementTypeId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStatementTypeId id) {
		this.id = id;
	}

}
