package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * UserSummaryByFileIoType generated by hbm2java
 */
public class UserSummaryByFileIoType implements java.io.Serializable {

	private UserSummaryByFileIoTypeId id;

	public UserSummaryByFileIoType() {
	}

	public UserSummaryByFileIoType(UserSummaryByFileIoTypeId id) {
		this.id = id;
	}

	public UserSummaryByFileIoTypeId getId() {
		return this.id;
	}

	public void setId(UserSummaryByFileIoTypeId id) {
		this.id = id;
	}

}
