package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * Version generated by hbm2java
 */
public class Version implements java.io.Serializable {

	private VersionId id;

	public Version() {
	}

	public Version(VersionId id) {
		this.id = id;
	}

	public VersionId getId() {
		return this.id;
	}

	public void setId(VersionId id) {
		this.id = id;
	}

}
