package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * WaitsByHostByLatency generated by hbm2java
 */
public class WaitsByHostByLatency implements java.io.Serializable {

	private WaitsByHostByLatencyId id;

	public WaitsByHostByLatency() {
	}

	public WaitsByHostByLatency(WaitsByHostByLatencyId id) {
		this.id = id;
	}

	public WaitsByHostByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsByHostByLatencyId id) {
		this.id = id;
	}

}
