package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * WaitsByUserByLatency generated by hbm2java
 */
public class WaitsByUserByLatency implements java.io.Serializable {

	private WaitsByUserByLatencyId id;

	public WaitsByUserByLatency() {
	}

	public WaitsByUserByLatency(WaitsByUserByLatencyId id) {
		this.id = id;
	}

	public WaitsByUserByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsByUserByLatencyId id) {
		this.id = id;
	}

}
