package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * WaitClassesGlobalByLatency generated by hbm2java
 */
public class WaitClassesGlobalByLatency implements java.io.Serializable {

	private WaitClassesGlobalByLatencyId id;

	public WaitClassesGlobalByLatency() {
	}

	public WaitClassesGlobalByLatency(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

}
