package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * WaitClassesGlobalByAvgLatency generated by hbm2java
 */
public class WaitClassesGlobalByAvgLatency implements java.io.Serializable {

	private WaitClassesGlobalByAvgLatencyId id;

	public WaitClassesGlobalByAvgLatency() {
	}

	public WaitClassesGlobalByAvgLatency(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByAvgLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

}
