package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final

/**
 * WaitsGlobalByLatency generated by hbm2java
 */
public class WaitsGlobalByLatency implements java.io.Serializable {

	private WaitsGlobalByLatencyId id;

	public WaitsGlobalByLatency() {
	}

	public WaitsGlobalByLatency(WaitsGlobalByLatencyId id) {
		this.id = id;
	}

	public WaitsGlobalByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitsGlobalByLatencyId id) {
		this.id = id;
	}

}
