package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.hostSummaryByStatementLatencyId;

/**
 * X.hostSummaryByStatementLatency generated by hbm2java
 */
public class X.hostSummaryByStatementLatency  implements java.io.Serializable {


     private X.hostSummaryByStatementLatencyId id;

    public X.hostSummaryByStatementLatency() {
    }

    public X.hostSummaryByStatementLatency(X.hostSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


