package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.hostSummaryByStagesId;

/**
 * X.hostSummaryByStages generated by hbm2java
 */
public class X.hostSummaryByStages  implements java.io.Serializable {


     private X.hostSummaryByStagesId id;

    public X.hostSummaryByStages() {
    }

    public X.hostSummaryByStages(X.hostSummaryByStagesId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStagesId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStagesId id) {
        this.id = id;
    }




}


