package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.innodbBufferStatsBySchemaId;

/**
 * X.innodbBufferStatsBySchema generated by hbm2java
 */
public class X.innodbBufferStatsBySchema  implements java.io.Serializable {


     private X.innodbBufferStatsBySchemaId id;

    public X.innodbBufferStatsBySchema() {
    }

    public X.innodbBufferStatsBySchema(X.innodbBufferStatsBySchemaId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsBySchemaId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsBySchemaId id) {
        this.id = id;
    }




}


