package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.innodbLockWaitsId;

/**
 * X.innodbLockWaits generated by hbm2java
 */
public class X.innodbLockWaits  implements java.io.Serializable {


     private X.innodbLockWaitsId id;

    public X.innodbLockWaits() {
    }

    public X.innodbLockWaits(X.innodbLockWaitsId id) {
       this.id = id;
    }
   
    public X.innodbLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.innodbLockWaitsId id) {
        this.id = id;
    }




}


