package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.innodbBufferStatsByTableId;

/**
 * X.innodbBufferStatsByTable generated by hbm2java
 */
public class X.innodbBufferStatsByTable  implements java.io.Serializable {


     private X.innodbBufferStatsByTableId id;

    public X.innodbBufferStatsByTable() {
    }

    public X.innodbBufferStatsByTable(X.innodbBufferStatsByTableId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsByTableId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsByTableId id) {
        this.id = id;
    }




}


