package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.ioGlobalByWaitByLatencyId;

/**
 * X.ioGlobalByWaitByLatency generated by hbm2java
 */
public class X.ioGlobalByWaitByLatency  implements java.io.Serializable {


     private X.ioGlobalByWaitByLatencyId id;

    public X.ioGlobalByWaitByLatency() {
    }

    public X.ioGlobalByWaitByLatency(X.ioGlobalByWaitByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByLatencyId id) {
        this.id = id;
    }




}


