package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.ioGlobalByFileByLatencyId;

/**
 * X.ioGlobalByFileByLatency generated by hbm2java
 */
public class X.ioGlobalByFileByLatency  implements java.io.Serializable {


     private X.ioGlobalByFileByLatencyId id;

    public X.ioGlobalByFileByLatency() {
    }

    public X.ioGlobalByFileByLatency(X.ioGlobalByFileByLatencyId id) {
       this.id = id;
    }
   
    public X.ioGlobalByFileByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByLatencyId id) {
        this.id = id;
    }




}


