package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.ioGlobalByFileByBytesId;

/**
 * X.ioGlobalByFileByBytes generated by hbm2java
 */
public class X.ioGlobalByFileByBytes  implements java.io.Serializable {


     private X.ioGlobalByFileByBytesId id;

    public X.ioGlobalByFileByBytes() {
    }

    public X.ioGlobalByFileByBytes(X.ioGlobalByFileByBytesId id) {
       this.id = id;
    }
   
    public X.ioGlobalByFileByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByBytesId id) {
        this.id = id;
    }




}


