package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import java.math.BigInteger;

/**
 * X.memoryGlobalTotal generated by hbm2java
 */
public class X.memoryGlobalTotal  implements java.io.Serializable {


     private BigInteger totalAllocated;

    public X.memoryGlobalTotal() {
    }

    public X.memoryGlobalTotal(BigInteger totalAllocated) {
       this.totalAllocated = totalAllocated;
    }
   
    public BigInteger getTotalAllocated() {
        return this.totalAllocated;
    }
    
    public void setTotalAllocated(BigInteger totalAllocated) {
        this.totalAllocated = totalAllocated;
    }




}


