package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.memoryByHostByCurrentBytesId;

/**
 * X.memoryByHostByCurrentBytes generated by hbm2java
 */
public class X.memoryByHostByCurrentBytes  implements java.io.Serializable {


     private X.memoryByHostByCurrentBytesId id;

    public X.memoryByHostByCurrentBytes() {
    }

    public X.memoryByHostByCurrentBytes(X.memoryByHostByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByHostByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByHostByCurrentBytesId id) {
        this.id = id;
    }




}


