package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.psDigest95thPercentileByAvgUsId;

/**
 * X.psDigest95thPercentileByAvgUs generated by hbm2java
 */
public class X.psDigest95thPercentileByAvgUs  implements java.io.Serializable {


     private X.psDigest95thPercentileByAvgUsId id;

    public X.psDigest95thPercentileByAvgUs() {
    }

    public X.psDigest95thPercentileByAvgUs(X.psDigest95thPercentileByAvgUsId id) {
       this.id = id;
    }
   
    public X.psDigest95thPercentileByAvgUsId getId() {
        return this.id;
    }
    
    public void setId(X.psDigest95thPercentileByAvgUsId id) {
        this.id = id;
    }




}


