package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.psDigestAvgLatencyDistributionId;

/**
 * X.psDigestAvgLatencyDistribution generated by hbm2java
 */
public class X.psDigestAvgLatencyDistribution  implements java.io.Serializable {


     private X.psDigestAvgLatencyDistributionId id;

    public X.psDigestAvgLatencyDistribution() {
    }

    public X.psDigestAvgLatencyDistribution(X.psDigestAvgLatencyDistributionId id) {
       this.id = id;
    }
   
    public X.psDigestAvgLatencyDistributionId getId() {
        return this.id;
    }
    
    public void setId(X.psDigestAvgLatencyDistributionId id) {
        this.id = id;
    }




}


