package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.psSchemaTableStatisticsIoId;

/**
 * X.psSchemaTableStatisticsIo generated by hbm2java
 */
public class X.psSchemaTableStatisticsIo  implements java.io.Serializable {


     private X.psSchemaTableStatisticsIoId id;

    public X.psSchemaTableStatisticsIo() {
    }

    public X.psSchemaTableStatisticsIo(X.psSchemaTableStatisticsIoId id) {
       this.id = id;
    }
   
    public X.psSchemaTableStatisticsIoId getId() {
        return this.id;
    }
    
    public void setId(X.psSchemaTableStatisticsIoId id) {
        this.id = id;
    }




}


