package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.schemaTableStatisticsId;

/**
 * X.schemaTableStatistics generated by hbm2java
 */
public class X.schemaTableStatistics  implements java.io.Serializable {


     private X.schemaTableStatisticsId id;

    public X.schemaTableStatistics() {
    }

    public X.schemaTableStatistics(X.schemaTableStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsId id) {
        this.id = id;
    }




}


