package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.schemaFlattenedKeysId;

/**
 * X.schemaFlattenedKeys generated by hbm2java
 */
public class X.schemaFlattenedKeys  implements java.io.Serializable {


     private X.schemaFlattenedKeysId id;

    public X.schemaFlattenedKeys() {
    }

    public X.schemaFlattenedKeys(X.schemaFlattenedKeysId id) {
       this.id = id;
    }
   
    public X.schemaFlattenedKeysId getId() {
        return this.id;
    }
    
    public void setId(X.schemaFlattenedKeysId id) {
        this.id = id;
    }




}


