package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.schemaTableStatisticsWithBufferId;

/**
 * X.schemaTableStatisticsWithBuffer generated by hbm2java
 */
public class X.schemaTableStatisticsWithBuffer  implements java.io.Serializable {


     private X.schemaTableStatisticsWithBufferId id;

    public X.schemaTableStatisticsWithBuffer() {
    }

    public X.schemaTableStatisticsWithBuffer(X.schemaTableStatisticsWithBufferId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsWithBufferId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsWithBufferId id) {
        this.id = id;
    }




}


