package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.schemaTableLockWaitsId;

/**
 * X.schemaTableLockWaits generated by hbm2java
 */
public class X.schemaTableLockWaits  implements java.io.Serializable {


     private X.schemaTableLockWaitsId id;

    public X.schemaTableLockWaits() {
    }

    public X.schemaTableLockWaits(X.schemaTableLockWaitsId id) {
       this.id = id;
    }
   
    public X.schemaTableLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableLockWaitsId id) {
        this.id = id;
    }




}


