package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.sessionId;

/**
 * X.session generated by hbm2java
 */
public class X.session  implements java.io.Serializable {


     private X.sessionId id;

    public X.session() {
    }

    public X.session(X.sessionId id) {
       this.id = id;
    }
   
    public X.sessionId getId() {
        return this.id;
    }
    
    public void setId(X.sessionId id) {
        this.id = id;
    }




}


