package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.statementsWithRuntimesIn95thPercentileId;

/**
 * X.statementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class X.statementsWithRuntimesIn95thPercentile  implements java.io.Serializable {


     private X.statementsWithRuntimesIn95thPercentileId id;

    public X.statementsWithRuntimesIn95thPercentile() {
    }

    public X.statementsWithRuntimesIn95thPercentile(X.statementsWithRuntimesIn95thPercentileId id) {
       this.id = id;
    }
   
    public X.statementsWithRuntimesIn95thPercentileId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithRuntimesIn95thPercentileId id) {
        this.id = id;
    }




}


