package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.statementAnalysisId;

/**
 * X.statementAnalysis generated by hbm2java
 */
public class X.statementAnalysis  implements java.io.Serializable {


     private X.statementAnalysisId id;

    public X.statementAnalysis() {
    }

    public X.statementAnalysis(X.statementAnalysisId id) {
       this.id = id;
    }
   
    public X.statementAnalysisId getId() {
        return this.id;
    }
    
    public void setId(X.statementAnalysisId id) {
        this.id = id;
    }




}


