package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.statementsWithSortingId;

/**
 * X.statementsWithSorting generated by hbm2java
 */
public class X.statementsWithSorting  implements java.io.Serializable {


     private X.statementsWithSortingId id;

    public X.statementsWithSorting() {
    }

    public X.statementsWithSorting(X.statementsWithSortingId id) {
       this.id = id;
    }
   
    public X.statementsWithSortingId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithSortingId id) {
        this.id = id;
    }




}


