package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.statementsWithErrorsOrWarningsId;

/**
 * X.statementsWithErrorsOrWarnings generated by hbm2java
 */
public class X.statementsWithErrorsOrWarnings  implements java.io.Serializable {


     private X.statementsWithErrorsOrWarningsId id;

    public X.statementsWithErrorsOrWarnings() {
    }

    public X.statementsWithErrorsOrWarnings(X.statementsWithErrorsOrWarningsId id) {
       this.id = id;
    }
   
    public X.statementsWithErrorsOrWarningsId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithErrorsOrWarningsId id) {
        this.id = id;
    }




}


