package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.userSummaryByStatementLatencyId;

/**
 * X.userSummaryByStatementLatency generated by hbm2java
 */
public class X.userSummaryByStatementLatency  implements java.io.Serializable {


     private X.userSummaryByStatementLatencyId id;

    public X.userSummaryByStatementLatency() {
    }

    public X.userSummaryByStatementLatency(X.userSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


