package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.userSummaryByFileIoTypeId;

/**
 * X.userSummaryByFileIoType generated by hbm2java
 */
public class X.userSummaryByFileIoType  implements java.io.Serializable {


     private X.userSummaryByFileIoTypeId id;

    public X.userSummaryByFileIoType() {
    }

    public X.userSummaryByFileIoType(X.userSummaryByFileIoTypeId id) {
       this.id = id;
    }
   
    public X.userSummaryByFileIoTypeId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByFileIoTypeId id) {
        this.id = id;
    }




}


