package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.userSummaryByStagesId;

/**
 * X.userSummaryByStages generated by hbm2java
 */
public class X.userSummaryByStages  implements java.io.Serializable {


     private X.userSummaryByStagesId id;

    public X.userSummaryByStages() {
    }

    public X.userSummaryByStages(X.userSummaryByStagesId id) {
       this.id = id;
    }
   
    public X.userSummaryByStagesId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStagesId id) {
        this.id = id;
    }




}


