package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.waitsGlobalByLatencyId;

/**
 * X.waitsGlobalByLatency generated by hbm2java
 */
public class X.waitsGlobalByLatency  implements java.io.Serializable {


     private X.waitsGlobalByLatencyId id;

    public X.waitsGlobalByLatency() {
    }

    public X.waitsGlobalByLatency(X.waitsGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsGlobalByLatencyId id) {
        this.id = id;
    }




}


