package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.waitClassesGlobalByAvgLatencyId;

/**
 * X.waitClassesGlobalByAvgLatency generated by hbm2java
 */
public class X.waitClassesGlobalByAvgLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByAvgLatencyId id;

    public X.waitClassesGlobalByAvgLatency() {
    }

    public X.waitClassesGlobalByAvgLatency(X.waitClassesGlobalByAvgLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByAvgLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByAvgLatencyId id) {
        this.id = id;
    }




}


