package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.waitClassesGlobalByLatencyId;

/**
 * X.waitClassesGlobalByLatency generated by hbm2java
 */
public class X.waitClassesGlobalByLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByLatencyId id;

    public X.waitClassesGlobalByLatency() {
    }

    public X.waitClassesGlobalByLatency(X.waitClassesGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByLatencyId id) {
        this.id = id;
    }




}


