package com.assignment.crudapp.entity;
// Generated Dec 22, 2021, 12:04:33 AM by Hibernate Tools 5.5.7.Final


import com.assignment.crudapp.entity.X.waitsByHostByLatencyId;

/**
 * X.waitsByHostByLatency generated by hbm2java
 */
public class X.waitsByHostByLatency  implements java.io.Serializable {


     private X.waitsByHostByLatencyId id;

    public X.waitsByHostByLatency() {
    }

    public X.waitsByHostByLatency(X.waitsByHostByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByHostByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByHostByLatencyId id) {
        this.id = id;
    }




}


